#!/bin/sh

session_dir="$HOME/IBM/iAccessClient/Emulator"
opts=$(printf "NEW\n%s" "$(find "$session_dir" -type f -name "*.hod" -print \
	| sed 's~.*/\(.*\)\..*~\1~')")

ans="$(printf "%s" "$opts" | dmenu -i -p "Which emulator to start?")"

if [ -f "$session_dir/$ans.hod" ]; then
	acs "$session_dir/$ans.hod"
elif [ "$ans" = "NEW" ]; then
	acs sm
fi
