#!/bin/sh

lock() {
  screen_size=$(xrandr | sed 's/[[:space:]]*\([[:digit:]]*x[[:digit:]]*\).*\*.*/\1/p;d')
  lock="/tmp/lock-image-$screen_size.png"
  if [ ! -e "$lock" ]; then
    tmp_mask="/tmp/lock-$$-mask.png"
    tmp_lock="/tmp/lock-$$-lock.png"
    convert -size "$screen_size" radial-gradient:none-black -sigmoidal-contrast 6,50% "$tmp_mask"
    convert "$DOTFILES_ROOT/wallpaper.jpg" -resize "$screen_size" "$tmp_lock"
    convert "$tmp_lock" +swap "$tmp_mask" -composite "$lock"
    rm -- "$tmp_mask"
    rm -- "$tmp_lock"
  fi

  i3lock -c "000000" -fei "$lock"
  sleep 60
  if pgrep i3lock > /dev/null; then
    xset dpms force off
  fi
}

if [ $# -gt 0 ]; then
  xset dpms force off
  sleep 5
  # If screen if still off then continue locking
  if xset -q | sed -n '${/[oO]ff/q;q1}'; then
    lock
  fi
else
  lock
fi

