#!/bin/sh

lock() {
  screen_size=$(xrandr | sed 's/[[:space:]]*\([[:digit:]]*x[[:digit:]]*\).*\*.*/\1/p;d')
  lock="/tmp/lock-image-$screen_size.png"
  if [ ! -e "$lock" ]; then
    convert "$DOTFILES_ROOT/wallpaper.jpg" -resize "$screen_size" "$lock"
  fi
  i3lock -c "000000" -fei "$lock"
  sleep 60
  if pgrep i3lock > /dev/null; then
    xset dpms force off
  fi
}

if [ $# -gt 0 ]; then
  xset dpms force off
  sleep 5
  # If screen if still off then continue locking
  if xset -q | sed -n '${/[oO]ff/q;q1}'; then
    lock
  fi
else
  lock
fi

