#!/bin/sh

window_id=$(xprop -root | sed 's/_NET_ACTIVE_WINDOW(WINDOW): window id # \(.*\)/\1/p;d')
if test "$window_id" != "0x0"; then
	window_name=$(xprop -id "$window_id" | sed 's/_NET_WM_NAME(UTF8_STRING) = \(.*\)/\1/p;d')
	ans=$(printf "NO\nYES" | dmenu -i -p "Type YES to kill $window_name")

	if test "$ans" = "YES"; then
		i3-msg kill
	fi
fi
