#!/usr/bin/env bash

IFS=x read -r width height <<< "$(xrandr \
  | sed 's/[[:space:]]*\([[:digit:]]*x[[:digit:]]*\).*\*.*/\1/p;d')"

test "$width" -gt 1024 && width=1024
test "$height" -gt 768 && height=768

screen_size="${width}x${height}"

rdesktop -g "$screen_size" -P -z -x 1 -r sound:off -u and DKSRV02
