#!/bin/sh

# Keyboard
setxkbmap us

# Monotor
xbacklight -set 100
if pgrep redshift; then
	killall -9 redshift
fi
redshift &

feh --bg-fill "$DOTFILES_ROOT/wallpaper.jpg"
compton --opengl --sw-opti --vsync opengl-swc --paint-on-overlay \
	-fb -i 0.8 -e 0.8 --no-fading-openclose --backend glx

# Adjust monitors on docking
dockd start

# Using cVim for chrome, start a small server so editing
#  text fields in vim is possible
cvim-server &

# Autolock
pid=$(pgrep xautolock)
if [ $? = 0 ]; then
	kill -9 "$pid"
fi
xautolock -time 5 -locker "lockscreen --delayed" &

# Volume
amixer sset Master mute
amixer sset Master 30%

# Clipboard
clipbored
