#!/bin/sh

current_id=$(i3-msg -t get_workspaces | jq '.[] | select(.focused) | .num')

append_layout() {
  i3-msg "append_layout $DOTFILES_ROOT/i3/workspace-$1.json"
}

case $current_id in
  7)
    append_layout "client"
    termite &
    termite &
    chromium &
    ;;
  8)
    append_layout "server"
    chromium &
    termite &
    acs "$HOME/IBM/iAccessClient/Emulator/DKSRV206.hod"
    ;;
  9)
    append_layout "music"
    deadbeef &
    termite -d ~/Music &
    ;;
  10)
    termite -e 'mutt' -t 'mutt-mail'
    ;;
esac
