#!/usr/bin/env bash

# $1 = filename
# $2 = type

file=$1
type=$2

case $type in
  html)
    cp -- "$file" "$file.html"
    lynx -dump "$file.html"
    rm -- "$file.html"
    ;;
  *)
    chromium "$file"
    ;;
esac
